export function giftTypeStock() {
    return [
      { abbr: 'Appliances', name: 'Appliances' },
      { abbr: 'Art', name: 'Art' },
      { abbr: 'Auto supplies', name: 'Auto supplies' },
      { abbr: 'Bed', name: 'Bed' },
      { abbr: 'Bedding', name: 'Bedding' },
      { abbr: 'Bookcases', name: 'Bookcases' },
      { abbr: 'Books', name: 'Books' },
      { abbr: 'Chairs', name: 'Chairs' },
      { abbr: 'Chests/contents', name: 'Chests/contents' },
      { abbr: 'Collections', name: 'Collections' },
      { abbr: 'Computer', name: 'Computer' },
      { abbr: 'Contents', name: 'Contents' },
      { abbr: 'Cookbooks', name: 'Cookbooks' },
      { abbr: 'Couches', name: 'Couches' },
      { abbr: 'Curios', name: 'Curios' },
      { abbr: 'Cutlery', name: 'Cutlery' },
      { abbr: 'Freezer', name: 'Freezer' },
      { abbr: 'Desk', name: 'Desk' },
      { abbr: 'Dishes', name: 'Dishes' },
      { abbr: 'Dryer', name: 'Dryer' },
      { abbr: 'Electrical appliances', name: 'Electrical appliances' },
      { abbr: 'Electronics', name: 'Electronics' },
      { abbr: 'Entertainment', name: 'Entertainment' },
      { abbr: 'Fireplace Items/Tools', name: 'Fireplace Items/Tools' },
      { abbr: 'Food', name: 'Food' },
      { abbr: 'Furniture', name: 'Furniture' },
      { abbr: 'Glasses', name: 'Glasses' },
      { abbr: 'Golf Clubs', name: 'Golf Clubs' },
      { abbr: 'Ironing Board', name: 'Ironing Board' },
      { abbr: 'Jewelry', name: 'Jewelry' },
      { abbr: 'Lamps', name: 'Lamps' },
      { abbr: 'Lawn Furniture', name: 'Lawn Furniture' },
      { abbr: 'Lawn Mower', name: 'Lawn Mower' },
      { abbr: 'Linens', name: 'Linens' },
      { abbr: 'Luggage', name: 'Luggage' },
      { abbr: 'Monitor', name: 'Monitor' },
      { abbr: 'Paintings', name: 'Paintings' },
      { abbr: 'Piano', name: 'Piano' },
      { abbr: 'Pictures', name: 'Pictures' },
      { abbr: 'Pots & Pans', name: 'Pots & Pans' },
      { abbr: 'Printer', name: 'Printer' },
      { abbr: 'Refrigerator/Freezer', name: 'Refrigerator/Freezer' },
      { abbr: 'Rugs', name: 'Rugs' },
      { abbr: 'Software', name: 'Software' },
      { abbr: 'Speakers', name: 'Speakers' },
      { abbr: 'Storage', name: 'Storage' },
      { abbr: 'Stove', name: 'Stove' },
      { abbr: 'Tables', name: 'Tables' },
      { abbr: 'Tools', name: 'Tools' },
      { abbr: 'Toys', name: 'Toys' },
      { abbr: 'TV', name: 'TV' },
      { abbr: 'Utensils', name: 'Utensils' },
      { abbr: 'Tools', name: 'Tools' },
      { abbr: 'Washing Machine', name: 'Washing Machine' },
      { abbr: 'Weed Wacker', name: 'Weed Wacker' },
      { abbr: 'Workbench', name: 'Workbench' },
      { abbr: 'Clothes', name: 'Clothes' },

    ];
  }

  export function matchGiftType(state, value) {
    return (
      state.name.toLowerCase().indexOf(value.toLowerCase()) !== -1 
      // state.abbr.toLowerCase().indexOf(value.toLowerCase()) !== -1
    );
  }